### ISSUE TITLE
More of a request for further information...

### ISSUE THREAD

**Issue by fecaleagle** [uroboro/NotificationExplorer#1]
So after installing NotificationExplorer from your repo, I fire up:

`cycript -p SpringBoard`

But then, when I try to access the UFSNotificationList, all I get is:

`throw new ReferenceError("Can't find variable: UFSNotificationList")`

I saw this before previously on a different device, and was able to resolve it by playing around a bit, but I can't for the life of me remember what I did to access the UFSNotificationList.  I've tried running cycript as mobile and root.  Any help you can provide as to how to actually pull access the list would be tremendously helpful.  Thanks!

Edit: Maybe this is an issue and not a just request for more info.  I just re-installed NotificationExplorer on the old device (iPhone 5, iOS 8.4), and it works as expected.  However, it fails on a newer device (iPhone 5s, iOS 9.0.2).  I will try a re-install from the repo, and then I will compile it from a clone.  Thanks!

Edit 2: Just compiled a clone in debug mode using a current version of [Theos](https://github.com/theos/theos) and I'm continuing to experience the same issue on 9.0.2.  Any thoughts about this?  I'm really curious to get a list of SpringBoard notifications from iOS 9.  Ah, getting a few MS errors about the extension not having a filter specified.  I'll add a filter for SpringBoard since that's all I care about right now and see if that straightens things out.

Edit 3: Adding an appropriate filter for com.apple.springboard fixes the issue for me.  Let me know your thoughts on this or if there's anything that can be done to restore the ability to hook all processes without explicitly setting a bundle identifier.

**Comment by uroboro** [comment]
Thank you for notifying me about this slip up. A solution since CydiaSubstrate's update is to filter for the Security framework, with which I'll be updating this project and the package on my repo.

**Comment by fecaleagle** [comment]
Thanks for your response.  Thanks also for the tip!  I have a tool (notification related) that also needs access to everything, and I wasn't sure how to specify the bundle filter.
